import cors, { type CorsOptions } from 'cors';
import type { Request, Response, NextFunction } from 'express';
import { config } from '@env/index';
import { logger } from '@logger/index';
import type TypeGuard from '@infra/app-type-helpers/type-guard';
import type TUnknownRecord from '@app-types/t-unknown-record';

const TYPE_CORS_ERROR = 'CORS_VIOLATION';

export class MyCorsError extends Error {
  public status = 403;
  public type = TYPE_CORS_ERROR;
  public blockedOrigin?: string;

  constructor(message: string, blockedOrigin?: string) {
    super(message);
    this.name = 'MyCorsError';
    this.blockedOrigin = blockedOrigin;
    // Important for correct operation of instanceof in TS/ES
    Object.setPrototypeOf(this, new.target.prototype);
  }
}

/**
 * CORS Policy:
 * - allowed origins are taken from config.corsAllowedOrigins
 * - credentials are enabled (if needed) — however, '*' cannot be used
 * - optionsSuccessStatus is toggled via config.corsLegacySupportImportant for correct operation of instanceof in TS/ES
 */

const allowedOrigins = config.corsAllowedOrigins;

const corsOptions: CorsOptions = {
  origin(origin, callback) {
    // origin === undefined -> non-browser request (curl, server-to-server)
    if (!origin) {
      callback(null, true);
      return;
    }

    if (allowedOrigins.includes(origin)) {
      callback(null, true);
    } else {
      callback(new MyCorsError(`CORS: origin ${origin} not allowed`, origin));
    }
  },
  methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'],
  allowedHeaders: ['Content-Type', 'Authorization', 'X-Requested-With'],
  credentials: true,
  optionsSuccessStatus: config.corsLegacySupport ? 200 : 204,
  preflightContinue: false,
};

export const corsMiddleware = cors(corsOptions);

/**
 * Additional middleware for logging and centralized handling of CORS errors.
 * Attached after corsMiddleware in the chain to catch errors generated by
 * cors (e.g., "Not allowed origin").
 */
export const corsErrorHandler = (err: unknown, req: Request, res: Response, next: NextFunction) => {
  if (!err) return next();
  if (isMyCorsError(err)) {
    logger.warn({ err: err.message, origin: req.headers.origin }, 'CORS blocked request');
    return res.status(403).json({ error: 'CORS policy: Access denied' });
  }
  next(err);
};

// Helpers
const isMyCorsError: TypeGuard<MyCorsError> = (value): value is MyCorsError => {
  return (
    !!value &&
    typeof value === 'object' &&
    (value instanceof MyCorsError || (value as TUnknownRecord).type === TYPE_CORS_ERROR)
  );
};
